/**
 * data.js — single source of truth for the storefront.
 *
 * IMPORTANT: All product + category data comes from public/api/*.json which is
 * generated by scripts/generate-api.mjs. We import those JSON files directly
 * here so that the initial React render and the live API fetch ALWAYS show the
 * same catalog. Previously, this file had its own hand-maintained product list
 * that diverged from the API — causing ghost products to appear in admin orders
 * but be invisible on the storefront. Never again.
 *
 * If you need to add/edit/remove products, edit scripts/generate-api.mjs and
 * run `npm run generate-api` (or just `npm run dev`/`npm run build`, which
 * regenerate automatically).
 */

import productsJson from '../public/api/products.json'
import categoriesJson from '../public/api/categories.json'

export const ALL_PRODUCTS = productsJson.data
export const CATEGORIES_DATA = categoriesJson.data

export const CITIES = [
  'Karachi','Lahore','Islamabad','Rawalpindi','Faisalabad',
  'Multan','Peshawar','Quetta','Sialkot','Hyderabad','Gujranwala','Other',
]
